import type { Metadata } from 'next';
import { Urbanist } from 'next/font/google';
import { Hero, Footer } from '@/components';
import './globals.css';

const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'EpicAnimax',
  description: 'Generated by create next app',
};

export default function RootLayout ({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <main className="max-w-7xl mx-auto bg-[#181A20]">
          <Hero />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
